export const DEFAULT_DIRECT_TAP_X = 0
export const DEFAULT_DIRECT_TAP_Y = 0

export const DEFAULT_DIRECT_SWIPE_FROM_X = 540
export const DEFAULT_DIRECT_SWIPE_FROM_Y = 1800
export const DEFAULT_DIRECT_SWIPE_TO_X = 540
export const DEFAULT_DIRECT_SWIPE_TO_Y = 600
export const DEFAULT_SWIPE_DURATION_MS = 400

export const POINTER_SWIPE_THRESHOLD_PX = 24
