import type { LanguageMode } from './settings'

export type Locale = 'en-US' | 'zh-CN'

export const APP_COPY = {
  'en-US': {
    settings: 'Settings',
    closeSettings: 'Close settings',
    close: 'Close',
    language: 'Language',
    languageSystem: 'System default',
    languageChinese: '中文',
    languageEnglish: 'English',
    appDescription:
      'Browser-based Android automation console for WebADB and OpenAI-compatible vision models.',
    githubRepository: 'GitHub repository',
    repositoryStats: 'Repository stats',
    stars: 'Stars',
    forks: 'Forks',
    openIssues: 'Open issues',
    githubStatsError: 'Could not load GitHub stats right now.',
    theme: 'Theme',
    themeSystem: 'System',
    themeLight: 'Light',
    themeDark: 'Dark',
    webUsbReady: 'ready',
    webUsbMissing: 'missing',
    model: 'Model',
    noModel: 'No model',
    modelSettings: 'Model settings',
    baseUrl: 'Base URL',
    apiKey: 'API Key',
    streamModelResponses: 'Stream model responses',
    device: 'Device',
    noDevice: 'No device',
    deviceDetails: 'Device details',
    serial: 'Serial',
    currentApp: 'Current app',
    package: 'Package',
    activity: 'Activity',
    keyboard: 'Keyboard',
    usbDebuggingRequired: 'USB debugging required',
    connect: 'Connect',
    disconnect: 'Disconnect',
    capture: 'Capture',
    installAdbKeyboard: 'Install ADB Keyboard',
    adbKeyboardInstalled: 'ADB Keyboard installed',
    enableAdbKeyboard: 'Enable ADB Keyboard',
    runDoctor: 'Run Doctor',
    doctorChecks: 'Doctor checks',
    doctorSummary: 'Doctor summary',
    installedApps: 'Installed apps',
    appSearch: 'App search',
    launchApp: 'Launch',
    launchInstalledApp: (name: string) => `Launch ${name}`,
    noInstalledApps: 'No installed apps found',
    deviceOptions: 'Device options',
    directCommands: 'Direct commands',
    directCommand: 'Direct command',
    tapX: 'Tap X',
    tapY: 'Tap Y',
    runTap: 'Run Tap',
    swipeFromX: 'From X',
    swipeFromY: 'From Y',
    swipeToX: 'To X',
    swipeToY: 'To Y',
    runSwipe: 'Run Swipe',
    directText: 'Text',
    runType: 'Run Type',
    runBack: 'Back',
    runHome: 'Home',
    runEnter: 'Enter',
    useAdbKeyboard: 'Use ADB Keyboard for text',
    confirmSensitiveActions: 'Confirm sensitive actions',
    sensitiveActionTitle: 'Sensitive action requested',
    sensitiveActionPrompt: 'Execute it?',
    actionSettle: 'Action settle (ms)',
    doubleTapInterval: 'Double tap interval (ms)',
    keyboardStep: 'Keyboard step (ms)',
    supportedActions: 'Supported actions',
    capabilities: [
      'Launch',
      'Tap',
      'Type',
      'Swipe',
      'Back',
      'Home',
      'Long press',
      'Double tap',
      'Wait',
      'Take over',
    ],
    androidScreenshot: 'Android screenshot',
    expandedAndroidScreenshot: 'Expanded screenshot for Android screenshot',
    screenshotInteractionLayer: 'Screenshot interaction layer',
    runGeneratedAction: 'Run generated action',
    clearGeneratedAction: 'Clear generated action',
    openScreenshotFor: (title: string) => `Open screenshot for ${title}`,
    screenshotDialogFor: (title: string) => `Screenshot for ${title}`,
    closeScreenshotPreview: 'Close screenshot preview',
    screenshotZoomControls: 'Screenshot zoom controls',
    zoomInScreenshot: 'Zoom in screenshot',
    zoomOutScreenshot: 'Zoom out screenshot',
    resetScreenshotZoom: 'Reset screenshot zoom',
    showPhoneFullscreen: 'Show phone fullscreen',
    exitPhoneFullscreen: 'Exit phone fullscreen',
    fullscreenPhonePreview: 'Fullscreen phone preview',
    noScreenshot: 'No screenshot',
    chat: 'Chat',
    conversation: 'Conversation',
    noMessages: 'No messages yet',
    chatMessage: 'Chat message',
    chatPlaceholder: 'Send a follow-up instruction...',
    taskTemplate: 'Task template',
    chooseTaskTemplate: 'Choose a template...',
    send: 'Send',
    newChat: 'New chat',
    maxSteps: 'Max steps',
    autoExecute: 'Auto execute',
    runOptions: 'Run options',
    plan: 'Plan',
    run: 'Run',
    stop: 'Stop',
    reset: 'Reset',
    export: 'Export',
    pendingAction: 'Pending action',
    step: 'Step',
    none: 'None',
    acknowledge: 'Acknowledge',
    finish: 'Finish',
    execute: 'Execute',
    user: 'User',
    assistant: 'Assistant',
    observation: 'Observation',
    runLog: 'Run Log',
    clear: 'Clear',
    noEvents: 'No events yet',
  },
  'zh-CN': {
    settings: '设置',
    closeSettings: '关闭设置',
    close: '关闭',
    language: '语言',
    languageSystem: '系统默认',
    languageChinese: '中文',
    languageEnglish: 'English',
    appDescription:
      '基于浏览器的 Android 自动化控制台，支持 WebADB 和 OpenAI 兼容视觉模型。',
    githubRepository: 'GitHub 仓库',
    repositoryStats: '仓库统计',
    stars: '星标',
    forks: '复刻',
    openIssues: '开放问题',
    githubStatsError: '暂时无法加载 GitHub 统计。',
    theme: '主题',
    themeSystem: '系统',
    themeLight: '浅色',
    themeDark: '深色',
    webUsbReady: '可用',
    webUsbMissing: '不可用',
    model: '模型',
    noModel: '未设置模型',
    modelSettings: '模型设置',
    baseUrl: 'Base URL',
    apiKey: 'API Key',
    streamModelResponses: '流式模型响应',
    device: '设备',
    noDevice: '无设备',
    deviceDetails: '设备详情',
    serial: '序列号',
    currentApp: '当前应用',
    package: '包名',
    activity: 'Activity',
    keyboard: '键盘',
    usbDebuggingRequired: '需要 USB 调试',
    connect: '连接',
    disconnect: '断开',
    capture: '截图',
    installAdbKeyboard: '安装 ADB 键盘',
    adbKeyboardInstalled: 'ADB 键盘已安装',
    enableAdbKeyboard: '启用 ADB 键盘',
    runDoctor: '运行 Doctor',
    doctorChecks: 'Doctor 检查',
    doctorSummary: 'Doctor 摘要',
    installedApps: '已安装应用',
    appSearch: '搜索应用',
    launchApp: '启动',
    launchInstalledApp: (name: string) => `启动 ${name}`,
    noInstalledApps: '没有找到应用',
    deviceOptions: '设备选项',
    directCommands: '直接设备命令',
    directCommand: '直接设备命令',
    tapX: '点击 X',
    tapY: '点击 Y',
    runTap: '执行点击',
    swipeFromX: '起点 X',
    swipeFromY: '起点 Y',
    swipeToX: '终点 X',
    swipeToY: '终点 Y',
    runSwipe: '执行滑动',
    directText: '文本',
    runType: '执行输入',
    runBack: '返回',
    runHome: '主页',
    runEnter: '回车',
    useAdbKeyboard: '文本输入使用 ADB 键盘',
    confirmSensitiveActions: '确认敏感动作',
    sensitiveActionTitle: '请求执行敏感动作',
    sensitiveActionPrompt: '是否执行？',
    actionSettle: '动作等待 (ms)',
    doubleTapInterval: '双击间隔 (ms)',
    keyboardStep: '键盘步进 (ms)',
    supportedActions: '支持的动作',
    capabilities: [
      '启动',
      '点击',
      '输入',
      '滑动',
      '返回',
      '主页',
      '长按',
      '双击',
      '等待',
      '接管',
    ],
    androidScreenshot: 'Android 截图',
    expandedAndroidScreenshot: '展开的 Android 截图',
    screenshotInteractionLayer: '截图交互层',
    runGeneratedAction: '执行生成的动作',
    clearGeneratedAction: '清除生成的动作',
    openScreenshotFor: (title: string) => `打开截图：${title}`,
    screenshotDialogFor: (title: string) => `${title}预览`,
    closeScreenshotPreview: '关闭截图预览',
    screenshotZoomControls: '截图缩放控件',
    zoomInScreenshot: '放大截图',
    zoomOutScreenshot: '缩小截图',
    resetScreenshotZoom: '重置截图缩放',
    showPhoneFullscreen: '全屏显示手机',
    exitPhoneFullscreen: '退出手机全屏',
    fullscreenPhonePreview: '全屏手机预览',
    noScreenshot: '暂无截图',
    chat: '聊天',
    conversation: '对话',
    noMessages: '暂无消息',
    chatMessage: '聊天消息',
    chatPlaceholder: '发送后续指令...',
    taskTemplate: '任务模板',
    chooseTaskTemplate: '选择模板...',
    send: '发送',
    newChat: '新聊天',
    maxSteps: '最大步数',
    autoExecute: '自动执行',
    runOptions: '运行选项',
    plan: '计划',
    run: '运行',
    stop: '停止',
    reset: '重置',
    export: '导出',
    pendingAction: '待处理动作',
    step: '步骤',
    none: '无',
    acknowledge: '确认',
    finish: '完成',
    execute: '执行',
    user: '用户',
    assistant: '助手',
    observation: '观察',
    runLog: '运行日志',
    clear: '清空',
    noEvents: '暂无事件',
  },
} as const

export type AppCopy = (typeof APP_COPY)[Locale]

export function resolveLocale(languageMode: LanguageMode): Locale {
  if (languageMode === 'zh-CN' || languageMode === 'en-US') {
    return languageMode
  }

  const browserLanguage =
    globalThis.navigator?.languages?.[0] ?? globalThis.navigator?.language ?? 'en-US'
  return browserLanguage.toLowerCase().startsWith('zh') ? 'zh-CN' : 'en-US'
}
